name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3



    - name: Install dependencies
      run: brew update&&brew install clang-build-analyzer --with-clang llvm &&make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
